### ISSUE TITLE
Worker deregister button is broken

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#212] opened 2019-09-09 12:04 UTC
Currently on master branch, the settings -> worker -> deregister worker button does not work.

**Comment by Skarlso** [comment] 2019-09-09 12:06
Oh My 😮

**Comment by Skarlso** [comment] 2019-09-20 11:50
I'll take care of this. Also, fix this vue warning while I'm there.

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <VueGoodTable>
       <ManageWorker>
         <TabPane> at node_modules/vue-bulma-tabs/src/TabPane.vue
           <Tabs> at node_modules/vue-bulma-tabs/src/Tabs.vue
             <Index> at src/views/settings/index.vue
               <AppMain> at src/components/layout/AppMain.vue
                 <Root>
```

**Comment by Skarlso** [comment] 2019-09-20 11:51
Oh, just saw you assigned this one already. :) Okay, have fun. :)

**Comment by Skarlso** [comment] 2019-09-20 11:51
@michelvocks Are you also taking care of the hot reload problem?

**Comment by michelvocks** [comment] 2019-09-20 13:44
@Skarlso You can overtake that. Currently busy with the docker pipeline execution.

**Comment by Skarlso** [comment] 2019-09-20 18:18
Cool. Will do. Thanks.

**Comment by Skarlso** [comment] 2019-09-21 21:11
So, I'm utter shit at javascript. But I think I know what the problem is.

Funnily enough, it's related to the above vue error. Basically, the periodic check causes a race on the data, an endless update loop. Because there is no comparison before assigning the data just clobbering it over again and again, which causes an update which overwrites the data, which causes an update... etc.

And the deregister is not working because said loop is overwriting the deregister action. I think. I tried JSON.stringify compare, but it only solved the issue temporarily and in a very ugly way. :)

I'll investigate further.

**Comment by Skarlso** [comment] 2019-09-30 10:37
Found the problem. We do this sort of thing in all of the front-end stuff but what's different here is the timestamp. The different timestamp causes an update feedback loop to the render because the data changes constantly.

I'll come up with something to that. Probably something like, removing that datapoint from the comparison. ¯\_(ツ)_/¯

**Comment by Skarlso** [comment] 2019-09-30 11:24
Uh, or not. I removed for now that completely, and it still seems to complain about that. WTH....

**Closed** 2019-10-07 17:35 UTC
Labels: bug
